### ISSUE TITLE
Cannot create backup via webhook

### ISSUE THREAD

**Issue by trych** [bnomei/kirby3-janitor#107]
Hi there,

thanks for the great plugin.

I am trying to call janitor's backup command via a webhook, but it throws an error. When I just insert the url in the browser, I get this:
<img width="1470" alt="20230312-153941_Screenshot_GoogleChrome" src="https://user-images.githubusercontent.com/9803905/224551971-0893c2c6-c665-46b3-af17-e09c18770c30.png">

The setup with the secret generally seems to work (if I mistype the secret, I get a 401 error) and I can also create the backup via panel button, but via webhook it gives me this error. Any idea what I could do? Thanks!

**Comment by bnomei** [comment]
fixed in https://github.com/bnomei/kirby3-janitor/commit/e141704c1600856f5cec6d50f2b31f449a3c71a4

**Comment by trych** [comment]
Thanks, this fixed it indeed.

My plan was to use wget or curl to actually *download* the resulting backupzip file, I missed that using the webhook just generates it. Could you let me know if janitor also allows to download this file after generation? If so, how could I go about this?
