### ISSUE TITLE
Download backupzip via webhook

### ISSUE THREAD

**Issue by trych** [bnomei/kirby3-janitor#108]
Hi there!

I added the backupzip button to one of my websites and now I would like to *download* this backupzip via a webhook (so I can run it from a local machine via cron). While the docs mention the code to download the backupzip

```php
Kirby\CLI\CLI::command('janitor:backupzip');
$backup = janitor()->data('janitor:backupzip')['path'];
if(F::exists($backup)) {
  Header::download([
    'mime' => F::mime($backup),
    'name' => F::filename($backup),
  ]);
  readfile($backup);
  die(); // needed to make content type work
}
```

I don't know where to place it and how to use it. Does this go into a route? How could I connect it to a webhook then so that I can still trigger it remotely using the secret?

Thanks!

**Comment by bnomei** [comment]
see updated readme

**Comment by bnomei** [comment]
janitors webhooks all return the json data so you need to use a custom one

**Comment by trych** [comment]
Gave it a try, works like a charm! Thank you so much!

**Comment by bnomei** [comment]
@trych thanks for the ☕️☕️☕️
