### ISSUE TITLE
Release of v4

### ISSUE THREAD

**Issue by ceesvanegmond** [bnomei/kirby3-janitor#117]
Hi @bnomei 

Could you please generate a log detailing the changes in version 4? I'm having trouble locating an upgrade path. Alternatively, could you create a CHANGELOG.md file? I'm keen to understand the modifications made from version 3 to version 4.

Thank you!

**Comment by bnomei** [comment]
what is an "upgrade path"?

changed version number to 4.
feature changes, none.
k4 specific bug fixes (disabled button state styling). 
codestyling changed from phpcsfixer to pint.

**Comment by ceesvanegmond** [comment]
An upgrade path is the upgrades that the user should do (in this case us) in order to be compatible with v4. For instance config that is changed and should be updated

**Comment by bnomei** [comment]
thanks for clarifying. no changes in you end should be needed whatsoever.
