### ISSUE TITLE
Download a file after custom process

### ISSUE THREAD

**Issue by afbora** [bnomei/kirby3-janitor#118]
Hey!

I'm trying to make a process that create custom zip file and download the zip file when client click the button. I tried with `janitor:download` and `job`, couldn't do that.

- `janitor:download` doesn't work because endpoint route is not a file, this is a process. After zip file created, download should be started. Returns 404 when I set the route that handle the zip file.
- `job` doesn't work because I can't start download process in a job or return download file path. Zip file created but download doesn't start.

Any help please?

**Comment by bnomei** [comment]
the readme provides documentation on how to setup a download. closing this old issue.
