### ISSUE TITLE
Help understanding the CLI environment 

### ISSUE THREAD

**Issue by squareclouds** [bnomei/kirby3-janitor#125]
hello there. I had used this plugin a few years ago, around 2022. now I see it has changed quite a lot! I dont really understand the whole CLI thing. does this mean that i have to install the cli on the shared server that hosts the live website for the plugin to work? again, from what it used to be it just feels a bit inaccessible and quite technical ^^"

**Comment by bnomei** [comment]
Hi, @squareclouds. I'm sorry for not getting back to you sooner.

The old version was based around the idea of "jobs." When Kirby introduced their commands and provided a few built-in commands for clearing the cache, etc., I decided that Janitors' "jobs" could all be represented as commands as well. This allows Janitor to run commands from other plugins without any required changes in these plugins to support Janitor.

I also think that many of the "jobs" run by Janitor are well suited to be run as CLI commands, with all the output glory it provides. Having a button in the Panel to do the same thing is usually the final step after the command has been fully implemented. Creating and debugging commands for the CLI is more accessible than debugging JSON responses.

I understand that using Composer and installing the CLI is a steeper learning curve, but I hope you will appreciate that decision given enough persistence.

**Comment by bnomei** [comment]
The Getkirby cli plugin is a wrapper around another lib that can be used in the CLI to create custom commands. The Janitor plugin uses it to allow you to write the command you want directly in the blueprint and have full support for the Kirby query language.

```yaml
janitor_callWithData:
  label: Call method on model with Data
  type: janitor
  command: 'janitor:call --method repeatAfterMe --data {{ user.id }}'
```

I included two command that keep the old spirit of calling jobs quickly: `janitor:job` and `janitor:call`. Both of them allow you to skip creating commands yourself (but Janitor will still need the CLI plugin to run them).

Having the Kirby CLI plugin installed as a dependency in not a security risk. If unsure, please get confirmation on this by asking in the official forum.

**Comment by squareclouds** [comment]
@bnomei thank you for your reply. yes i will post in the cli repo then, since i dont still fully understand if i can do all of this without much problems on a shared hosting server where you cannot really install things.

**Comment by bnomei** [comment]
The CLI is just a PHP script, even if wrapped as a bin.

https://github.com/getkirby/cli/blob/main/bin/kirby

**Comment by squareclouds** [comment]
sorry to answer you here even though it is a bit off-topic, but again, it is just not easy to understand what one must do to make the CLI work if one is unfamiliar with composer and is used to install all plugins just be downloading the zip and putting it in the plugins folder :/ dont i have to run all those things on the live server? i already asked in the CLI repo though

![Bildschirmfoto 2024-07-22 um 18 58 09](https://github.com/user-attachments/assets/15146ba5-36d3-4af2-b7d1-dfbb20c0ff47)
