### ISSUE TITLE
Using changeSlug in a job breaks panel reload

### ISSUE THREAD

**Issue by mrflix** [bnomei/kirby3-janitor#128]
I'm using a janitor button to fetch data from an API to prefill page content. The data includes the page title. So I want to update the slug too. And reload the panel view after all is done. But changing the slug in the job breaks the panel reload because the page doesn't exist anymore under the old slug.

I don't see this as a bug-report because it seems like quite the edge case. It's rather a write down and to see if others run into this too.

I found this [forum post](https://forum.getkirby.com/t/i-figured-a-way-to-automatically-change-slugs-and-handle-redirect-properly-in-the-panel/23825) where ktryn is sharing a solution to handle the redirect after changing the slug. Unfortunately it was reported that it broke with version 3.6.

**Comment by Andrez092** [comment]
maybe this will help
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
If you don't have the c compliator, install it.(gcc or clang)

**Comment by bnomei** [comment]
thanks for contributing.
