### ISSUE TITLE
command not found: kirby

### ISSUE THREAD

**Issue by Messa1** [bnomei/kirby3-janitor#129]
I installed based on the doc on my local env. your plugin.

`composer require getkirby/cli bnomei/kirby3-janitor`

```
{
  "require": {
    "php": "~8.1.0 || ~8.2.0 || ~8.3.0",
    "getkirby/cms": "^3.10",
    "getkirby/cli": "^1.5",
    "bnomei/kirby3-janitor": "^4.0"
  },
```
I reload terminal on my mac and try kirby as cli command.
And got this error.

`command not found: kirby`

Maybe you have an idea. I'm using right now kirby 3 on this page - update is planed but not know :)

**Comment by Messa1** [comment]
Oky - Im not sure, but maybe cli works - if i try 

![Bildschirmfoto 2024-10-18 um 09 07 32](https://github.com/user-attachments/assets/591be68c-ee09-4930-a262-b4ea9f77b87d)


```
`Kirby::plugin('plugin/pluginname', [
  'commands' => [
    'eport-exportdata:export' => [
      'description' => 'Nice command',
      'args' => [],
      'command' => function ($cli) {
        $cli->success('My first plugin command');
        janitor()->data($cli->arg('command'), [
          'status' => 200,
          'message' => 'My first plugin command' . $cli->arg('data'),
      ]);
      }
    ]
  ]
]);
```

**Comment by bnomei** [comment]
to run `kirby` as a command locally you need to install it locally as a global composer dependency. see their readme on how to do so.

for the setup described in janitors readme you would need to call the kirby PHP binary as `vendor/bin/kirby` as in

**in project root**
```shell
vendor/bin/kirby --version
```

inside the janitor commands/blueprint you do not need to prefix them with the binary.
