### ISSUE TITLE
Blueprint field : add target option

### ISSUE THREAD

**Issue by jobdr** [bnomei/kirby3-janitor#20]
Hi,

First, thanks for your plugin. 👌 

Is it possible to add in the blueprint field an option for `target` attribute ? 
It would be better if we gave the option to open a link or a file in a new window.

Thanks

**Comment by bnomei** [comment]
that might trigger a popup warning from most browsers but i will see what i can do.

current code here. feel free to PR something that worked for you.
https://github.com/bnomei/kirby3-janitor/blob/master/src/components/fields/Janitor.vue#L98

**Comment by bnomei** [comment]
https://github.com/bnomei/kirby3-janitor/wiki/Panel-Field-Option:-intab

**Comment by bnomei** [comment]
https://github.com/bnomei/kirby3-janitor/releases/tag/v2.4.3
