### ISSUE TITLE
Help message in field

### ISSUE THREAD

**Issue by jklue** [bnomei/kirby3-janitor#23]
Is there a way to add `help:` text to the Janitor button field? I want to explain what's going to happen when clicked. Or should I just add an info field above.

**Comment by bnomei** [comment]
i need to investigate how to create a proper help secetion for fields with vue to match kirbys core but i would love to delay this until the new UI kit for panel is done, so in the meantime please use a field with type `info`. but i agree a help section is a useful addition.

**Comment by bnomei** [comment]
maybe even allow help text to change based on json repsonse.

**Comment by bnomei** [comment]
maybe @johannschopplich is willing to PR a solution for adding a help message below the button. he was kind enough to redo most of my messy vue code before. but i will create a feature release later today so best not get started right away.

**Comment by bnomei** [comment]
`help` has been available for a while now in janitor. closing this old issue.
