### ISSUE TITLE
Call from file blueprint

### ISSUE THREAD

**Issue by S1SYPHOS** [bnomei/kirby3-janitor#26]
Hey there,
maybe I'm missing something, but how would I access a file when placing janitor button inside a file blueprint?

Thank you very much!
S1S

**Comment by bnomei** [comment]
it was not possible before but now it is.

https://github.com/bnomei/kirby3-janitor/wiki/HowTo:-with-File-Blueprints

**Comment by S1SYPHOS** [comment]
Aren't you the best! THX!
