### ISSUE TITLE
Bug? JSON Response shown in button

### ISSUE THREAD

**Issue by andreasotto** [bnomei/kirby3-janitor#28]
When executing a custom job, i'll receive this result:

![image](https://user-images.githubusercontent.com/2129515/89062185-4b334e80-d366-11ea-8555-be3cfbfbcb78.png)

That doesn't look so well.

**Comment by andreasotto** [comment]
Update:

The example on https://github.com/bnomei/kirby3-janitor/wiki/HowTo:-Custom-Jobs contains a 

 `'label' => $page->title()`

that should be 

 `'label' => $page->title()->value()`

**Comment by bnomei** [comment]
fixed the typo in wiki. please close it you think that solves it.
