### ISSUE TITLE
Wrong label content after "cooling down"

### ISSUE THREAD

**Issue by andreasotto** [bnomei/kirby3-janitor#29]
When you click the button while it is "cooling down" from a failed response (`!= 200`) it will contain the wrong label content. Instead of the original label content the error label content is shown permanently.

**Comment by bnomei** [comment]
maybe it should not be clickable at all while on cooldown?

**Comment by andreasotto** [comment]
Yes, thats correct. It should not be clickable, i agree. That would be the best solution.
