### ISSUE TITLE
"quiet" argument for CLI

### ISSUE THREAD

**Issue by PatricB** [bnomei/kirby3-janitor#31]
Nice plugin!!!
I would love to see a argument like "-q --quiet" for running jobs silently as long as no error occurs.

**Comment by bnomei** [comment]
each job has full access to the cli lib. so could do that "quiet" option for my own jobs but you will have to implement the same checks for your own. i will try to find some time to add this... but i am on parental leave right now so it might take a while.

**Comment by bnomei** [comment]
`-q --quiet` will be added in next release later today.
