### ISSUE TITLE
Dialogue boxes

### ISSUE THREAD

**Issue by S1SYPHOS** [bnomei/kirby3-janitor#49]
Follow up from Discord:

Are you thinking what I'm thinking, like: I'm telling janitor what fields I need and upon pressing a button, I'm prompted for those fields, and then I can use the entered information inside a job? That would be AWESOME!

**Comment by bnomei** [comment]
thats the plan. i will give it a try some day in august or early september. but if any vue-wizard wants to PR before that, be my guest.

**Comment by S1SYPHOS** [comment]
Well, being no vue-wizard, I'll keep an eyes open. This will be great, though!

**Comment by bnomei** [comment]
kirby can do custom dialogs on dropdown events etc. that should be good enough. i tried to get it working but failed so far.
https://forum.getkirby.com/t/how-to-create-custom-file-dropdown-and-dialog/24921

**Comment by S1SYPHOS** [comment]
Did you implement this? Or maybe I'm too dumb to realise it 😃

**Comment by bnomei** [comment]
i did not implement this for janitor. i think creating a custom dropdown on page/file objects can be could be done in kirby easily enough (also i dont undertsand how and there is no cookbook for that yet).
if one really needs a fully functional dialog having a janitor as a dependencies for just having a button seems overkill to me. 

so i decided to learn how to do dropdowns for now and add nothing to janitor.

**Comment by S1SYPHOS** [comment]
Thanks for letting me know, @bnomei
