### ISSUE TITLE
option to disable set_time_limit()

### ISSUE THREAD

**Issue by moevbiz** [bnomei/kirby3-janitor#51]
Thanks a lot for this plugin!

my remote server provider doesn't like that Janitor uses `set_time_limit()` at line `134` in `/classes/Janitor.php`. Commenting that line out makes everything work well without any issue. 

Is there any chance to have disabling this function built into the plugin as a setting, so that a future update won't break my nice download button? :~)

**Comment by bnomei** [comment]
does it throw an exception? can you send me the message or a screenshot? i will most probably wrap it in try-catch but would love to do it as clean as possible.

**Comment by moevbiz** [comment]
yes, it threw an exception, should have said so! Much better to have try/catch, it works now, thanks a lot for the quick fix!

**Comment by bnomei** [comment]
all good
