### ISSUE TITLE
Note down that Clipboard API is available only in SecureContext

### ISSUE THREAD

**Issue by adamkiss** [bnomei/kirby3-janitor#61]
`Navigator.clipboard` is available only in secure context - i.e. HTTPS active or localhost (not local domain, actual localhost).

- https://github.com/bnomei/kirby3-janitor/wiki/Panel-Field:-Copy-to-Clipboard
- https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API#interfaces

**Comment by bnomei** [comment]
thanks @adamkiss   i will do that asap

**Comment by bnomei** [comment]
done

**Comment by adamkiss** [comment]
😂 at the "asap", @bnomei 👍🏻
