### ISSUE TITLE
Problems on subpages.

### ISSUE THREAD

**Issue by sigistardust** [bnomei/kirby3-janitor#62]
Hello there, 

I have a problem with the janitor button on subpages (children of site children). It works on all pages, except on subpages. 
Interestingly, it works on my local environment, but not in production. 

This is my code:
```
'bnomei.janitor.jobs' => [
      'copy' => function (Kirby\Cms\Page $page = null, string $data = null) {
          $kirby = kirby();
          $kirby->impersonate('kirby');
  
          if ($page === null) {
              $page = site()->index(true)->findByID($data); 
          }
          $languages = kirby()->languages();
          $language = $languages->not(kirby()->language())->first()->code();
          $content = $page->text()->toString();
          $page->update(['text' => $content], $language);
          return [
              'status' => 200,
              'label' => 'Kopiert.',
          ];
      },
    ],
```

After clicking the copy button, I get `Call to a member function text() on null` and error code 500. Does anyone have an idea, what the issue might be? If I can provide any other information, let me know.

I use Kirby version 3.6.0 and PHP version 8.0.0 on an Apache Server.

Thanks for the great work on this plugin!

**Comment by bnomei** [comment]
as far as i can tell. the `$page` could only be null and stay null if you are working on a page in draft mode but do not forward the `page.id` as data.

https://github.com/bnomei/kirby3-janitor/wiki/HowTo:-Custom-Jobs#working-with-page-objects-in-draft-mode
```
 janitor:
    type: janitor
    label: Kopieren
    job: copy # NAME OF YOUR JOB
    data : '{{ page.id }}' # THIS IS NEEDED TO FIND THE DRAFT
```

if thats not the issue i would need a content and blueprint setup to replicated.
