### ISSUE TITLE
Allow camelCase jobs

### ISSUE THREAD

**Issue by S1SYPHOS** [bnomei/kirby3-janitor#7]
Hey there,
I'd like to see camelCase jobs working, I just tested `downloadImage` (doesn't work) against `downloadimage` (works).

Thank you for this very helpful plugin!
Cheers,

S1SYPHOS

// Edit:
And maybe jobs like this, too: `download_image`

**Comment by bnomei** [comment]
oh boy. sure i will fix that. thanks for reporting.

**Comment by S1SYPHOS** [comment]
That's quite useful, I'm looking forward to the `$page` object, really!
I praise your work, period.

**Comment by S1SYPHOS** [comment]
Works as expected, thanks!
