### ISSUE TITLE
CLI 8.0

### ISSUE THREAD

**Issue by iskrisis** [bnomei/kirby3-janitor#72]
I am getting
```
TypeError: array_merge(): Argument #2 must be of type array, null given in file /.../site/plugins/kirby3-janitor/classes/Janitor.php on line 37
```
 when trying to use the CLI. Both my machine and server are PHP8.0. 
It's line
```php
$extends = array_merge($this->options['jobs-defaults'], $this->options['jobs-extends']);
```
but when i get $this->options after defaults merge
```php
array:6 [[▼]()
  "debug" => null
  "log" => null
  "jobs" => null
  "jobs-defaults" => array:1 [[▶]()]
  "jobs-extends" => null
  "secret" => null
]
```
So i am not loading the generated index. Surprisingly what fixes it is if i do 
```
php site/plugins/kirby3-janitor/janitor --kirby .
```
now what i don't understand is that `.` should be same as `pwd` and if i put the absolute path from `pwd` it doesn't work.

Also this is happening on both linux and mac. Kind of wierd that `.` fixes it for me?

**Comment by bnomei** [comment]
you dont have to use the `--kirby .`. janitor will try a few standard folders anyway. the public folder setup should work without `--kirby`.
https://github.com/bnomei/kirby3-janitor/blob/5df91d66a5628576a6f7c7ae3871f012f06166e4/janitor#L85

in which folder are you calling janitor? i assume the root of project.
janitor will try to copy the public/index.php and janitor-HASH.php. can you share that with me?
