### ISSUE TITLE
Inconsistent compatibility information

### ISSUE THREAD

**Issue by nilshoerrmann** [bnomei/kirby3-janitor#79]
In `composer.json`, this plugin is marked as compatible with PHP >= `7.4.0`. After installing the latest version, composer complains though that it requires PHP 8.0.2:

https://github.com/bnomei/kirby3-janitor/blob/f00fb2d2d5d1cad9fdd6d0e9f3f9bb508b97a5e1/vendor/composer/platform_check.php#L7-L9

**Comment by bnomei** [comment]
probably because i did run composer locally on a php 8 env. will fix asap.
