### ISSUE TITLE
make page object available in job

### ISSUE THREAD

**Issue by bnomei** [bnomei/kirby3-janitor#8]
if job route was issued from a panel button.

https://forum.getkirby.com/t/using-page-variable-in-config-php-janitor-plugin/14236

**Comment by S1SYPHOS** [comment]
Totally useful, I'm absolutely interested in this!

**Comment by bnomei** [comment]
page object is now available in the job. see [example](https://github.com/bnomei/kirby3-janitor#custom-jobs)

```php
'heist' => function(Kirby\Cms\Page $page = null, string $data = null)
```

**Comment by bnomei** [comment]
as a bonus i added a new prop `data`to the field which you can forward data from the blueprint to the job if needed.

**Comment by lukehatfield** [comment]
Loving this plugin (using it to translate pages at will). One issue though--the `$page` object is null when the current page is in draft status. Is there a way around that?

**Comment by bnomei** [comment]
> Loving this plugin (using it to translate pages at will). One issue though--the `$page` object is null when the current page is in draft status. Is there a way around that?

its using the `page` helper to get the page object.
https://github.com/bnomei/kirby3-janitor/blob/0a905810b3d17401bf0280f8342c8b024e493018/classes/Janitor.php#L137

retrieving a non direct subchild draft is a not easy in kirby (yet?). so i do not have a good out of the box solution for that yet.
https://forum.getkirby.com/t/cant-get-draft-subpage-with-findpageordraft/14346

but you should be able to use the data prop to forward the targets diruri and retrieve the draft in you job yourself (without relying on the page object janitor forwards to the callback).

**Comment by lukehatfield** [comment]
Aha! I found [this workaround](https://github.com/bnomei/kirby3-janitor/wiki/HowTo:-Custom-Jobs#working-with-page-objects-in-draft-mode) that you refer to. Thank you!

**Comment by PatricB** [comment]
@bnomei couldn't you use `kirby()->page()` to get the the page even if has draft status?

**Comment by PatricB** [comment]
> @bnomei couldn't you use `kirby()->page()` to get the the page even if has draft status?

Ah! Now saw the workaround @lukehatfield mentioned and I understand.
