### ISSUE TITLE
working with draft pages

### ISSUE THREAD

**Issue by jaro-io** [bnomei/kirby3-janitor#80]
hey there 🌻 ✨ 
i was just trying to get a draft page by using `data: '{{ page.id }}'`. first of all, the basic solution `->findById()` from the wiki page has been deprecated. so i was trying with `->findPageOrDraft()` first. but [looks like](https://forum.getkirby.com/t/cant-get-draft-subpage-with-findpageordraft/14346/2) this only works for direct children. so i just thought i’d post this here in case anyone else struggles with it.

```php
$page = site()->findPageOrDraft($data);   //not working
$page = site()->index(true)->find($data); //working
$page = kirby()->page($data, null, true); //working
```

to get a more performant solution, i also tried with the auto id plugin. but so far the suggested solution from the wiki page doesn’t seem to work. there is even an info [in the auto id wiki](https://github.com/bnomei/kirby3-autoid/wiki/PHP:-autoid(),-Field-Method-fromAutoID()#create-a-pagefile-programmatically-and-retrieve-autoid) that says the `autoid()` helper function "will not find drafts". so i am confused now. any thoughts @bnomei?

thank youuu!
♥️

**Comment by bnomei** [comment]
you could use `{{ page.diruri }}` and `bolt($data)` from my bolt plugin.

**Comment by jaro-io** [comment]
i am currently not using the bolt plugin in my build, only autoid. but i still cant get any draft page with `autoid($autoid)`. its always returning `null`. as soon as i publish the page, the same code works fine. maybe more an issue for the autoid repo?

**Comment by bnomei** [comment]
i checked the autoid code again. you are right it does not work for retrieving drafts. i am not sure yet if i consider will fix it though since k3.8 will have uuids that will make the autoid plugin obsolete anyway.

**Comment by jaro-io** [comment]
makes total sense. yeah let’s wait for what the kirby team publishes next. anyway, thanks for standing by and being so helpful! 🪂 ✨
