### ISSUE TITLE
syntax error, unexpected token ")"

### ISSUE THREAD

**Issue by theamnesic** [bnomei/kirby3-janitor#85]
Hi, 

With Kirby 3.5.7, php 8.0.8, Janitor 2.16.2, I've got the  `syntax error, unexpected token ")"` error alert on this tasks : 
- `cleanCache`
- `flushSessions`
- `render`
- `thumbs`
- `backupZip`

`flushPages` works.

Switching to php 7.4 give this error : `syntax error, unexpected '|', expecting variable (T_VARIABLE)`.

Console error : `GET https://mysite.com/api/plugin-janitor/cleanCache/%24 500 (Internal Server Error)`

`https://mysite.com/api/plugin-janitor/cleanCache/` return `{"status":"error","message":"Unauthenticated","code":403,"key":"error.permission","details":[]}`

Any idea?

____

Edit : I'm using composer to update. When I download the files via Github instead of `composer update`, it's working.

**Comment by saschen** [comment]
Hi, 
same problem with Kirby 3.6.6.1 and PHP 8.0.23-he.0

**Comment by bnomei** [comment]
i need a bit more information to debug this since i can not replicate it myself.

1) how are you calling the janitor job? panel button or CLI?
2) is it the browser js console you are referring to? how did the GET request get triggered? via the panel button, right?
3) if the errors are thrown, could you turn on kirbs debugging so i can get a filename and preferable line number?
4) whats your dev setup like? osx with mamp etc...

you can not call the endpoint manually (without the setup for a secret... see wiki) thats why the auth error is thrown in that case.

**Comment by theamnesic** [comment]
Hi, 

Updated to Kirby 3.8.2 and Janitor 3.2.0 installed via .zip file, error is now `Class "Kirby\CLI\CLI" not found`.

**Comment by bnomei** [comment]
janitor 3 needs kirby cli which can inly be installed with composer

**Comment by theamnesic** [comment]
I've just installed with composer with `composer require getkirby/cli bnomei/kirby3-janitor`.

Now the error is : `Undefined constant "STDOUT"` in all the tasks, even the `flushPages`.

**Comment by bnomei** [comment]
the core commands from the cli are aimed to print to the console. 

unless you run these commands with the `--quiet` parameter, which was recently introduced, it tries to write to the console when there is none (calling from the panel).

i created `janior:flush --name pages` to allow same functionallity in the panel.

see
https://github.com/bnomei/kirby3-janitor/blob/master/commands/flush.php

**Comment by bnomei** [comment]
i had brought that issue to the teams attention, the fix is easy enough, but sadly it did not make it in the most recent update. 


feel free to upvote my issue there:
https://github.com/getkirby/cli/issues/21

**Comment by theamnesic** [comment]
Hi @bnomei!

Any news on this since CLI 1.1.0 add the `New global --quiet option to suppress the output of the command`?
