### ISSUE TITLE
Backup job destination

### ISSUE THREAD

**Issue by S1SYPHOS** [bnomei/kirby3-janitor#88]
Hey there,
*technically* the backup location is not 'site/backups' but 'one directory up from accounts', which is why I just spend ten minutes figuring out where the hell my backups are located - in my case `accounts` resides below `storage` (along with `cache` and `sessions`), so maybe the could

1) change code
2) change wiki

.. to calrify this :smile:
As always, I'm not afraid of opening PRs and stuff!

Cheers
S1SYPHOS

**Comment by bnomei** [comment]
added note in wiki
