### ISSUE TITLE
Error in panel

### ISSUE THREAD

**Issue by LeBenLeBen** [bnomei/kirby3-janitor#9]
With version 1.4.0 installed through Composer on a Kirby 3.2 instance, I get the following error in the panel:

```
Error: Cannot find module 'function () {var a={name:"Janitor",props:{label:String,progress:String,job:String,cooldown:Number,status:String,data:String,pageURI:String},methods:{janitor:function(){var t=this.job;t=t+"/"+encodeURIComponent(this.pageURI),null!=this.data&&(t=t+"/"+encodeURIComponent(this.data)),this.getRequest(t)},getRequest:function(t){var s=this,e=this.label;this.label=this.progress.length>0?this.progress:this.label+"...",this.status="doing-job",this.$api.get(t).then(function(t){void 0!==t.label&&(s.label=t.label),void 0!==t.status?s.status=200==t.status?"is-success":"has-error":s.status="has-response",setTimeout(function(){s.label=e,s.status=""},s.cooldown)})}}};if(typeof a==="function"){a=a.options}Object.assign(a,function(){var render=function(){var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c("k-button",{staticClass:"janitor",class:_vm.status,attrs:{"job":_vm.job},on:{"click":function($event){return _vm.janitor()}}},[_vm._v(_vm._s(_vm.label))])};var staticRenderFns=[];return{render:render,staticRenderFns:staticRenderFns,_compiled:true,_scopeId:null,functional:undefined}}());panel.plugin("bnomei/janitor",{fields:{janitor:a}});}'
```

From the file media/plugins/index.js line 37

It breaks all my custom fields for some reason. If I disable the plugin everything works fine again.

The blueprint looks like this:

```yml
janitor:
  type: janitor
  label: Vider le cache
  progress: Nettoyage en cours…
  job: clean
```

In the panel, where the button is supposed to show up, Kirby throws:

```
 The field type "janitor" does not exist
```

Let me know what extra info would help you debug this issue.

**Edit:** with Kirby 3.1.x everything works fine.

**Comment by bnomei** [comment]
works fine on my local setup. will test remote next. in meantime...
have you tried clearing the browser cache to refresh the js file the panel creates? sometimes a restart of firefox seems to be required.

**Comment by bnomei** [comment]
remote setup works fine with kirby 3.2.0 and plugin 1.4.0.

**Comment by LeBenLeBen** [comment]
I've cleared my cache, restarted the browser, even tried in other browsers where I've never opened the panel, the bug is still present. It doesn't seems to be cache related as modifying the index.js can be seen in the browser.

I tried to add a `!` at the beginning of the plugin `index.js` — I saw that in other plugins — and it actually fixed the issue for some reason. I guess Kirby plugins loader doesn't like expressions that returns `undefined` (the `!` makes the expression return `true` instead).

I didn'd find any related issue in Kirby repo or information in the docs or the forum, I'll try to ask on Slack.

**Comment by bnomei** [comment]
please do that. the `/index.js ` is build by parcel (since 1.4). before that i used webpack so maybe that caused the change.

**Comment by bnomei** [comment]
before this drives you nuts you can always downgrad in composer in setting or use a release zip. like 1.3.0 https://github.com/bnomei/kirby3-janitor/tree/v1.3.0

**Comment by bnomei** [comment]
before this drives you nuts you can always downgrade in composer or use a release zip. like 1.3.0 https://github.com/bnomei/kirby3-janitor/tree/v1.3.0

**Comment by bnomei** [comment]
@LeBenLeBen seems like other plugins might cause this. pleas check if you have like timeoettings/kirby-color installed. see 
https://github.com/getkirby/ideas/issues/135

**Comment by LeBenLeBen** [comment]
The issue seems to be caused by [kirby-builder](https://github.com/TimOetting/kirby-builder) in my case, which doesn't include a semi-colon at the end of its `index.js`,

There seems to be an issue already open: https://github.com/TimOetting/kirby-builder/issues/126
