### ISSUE TITLE
The Toolkit\Query class has been deprecated

### ISSUE THREAD

**Issue by vauvarin** [bnomei/kirby3-janitor#95]
With the release of Kirby 3.9.0, the Toolkit\Query class has been deprecated and should be replaced by Query\Query.

**Comment by vauvarin** [comment]
This is what is deprecated:

   - Old Kirby\Toolkit\Query has been deprecated and will be removed in Kirby 3.10.0. Use Kirby\Query\Query instead, e.g.Query::factory($query)->resolve($data).

    - new Query($query, $data): Passing $data to constructor will be deprecated. Use (new Query($query))->resolve($data) instead.

    - Query::result() will be deprecated. Use $query->resolve($data) instead.

You can check the PR here: https://github.com/getkirby/kirby/pull/4626

**Comment by bnomei** [comment]
thanks @vauvarin 

that should be fine in v3 of plugin by now. i wont patch v2.

https://github.com/bnomei/kirby3-janitor/blob/eaa6e5510e5f08c3902724cc98751ab0a34a727c/commands/render.php#L14)
